[package]
name = "py32-hal"
version = "0.1.1"
edition = "2021"
authors = ["Decaday <myDecaday@outlook.com>", "Andelf <andelf@gmail.com>"]
repository = "https://github.com/py32-rs/py32-hal"
documentation = "https://docs.rs/py32-hal"
homepage = "https://github.com/py32-rs/py32-hal"
categories = ["embedded", "no-std", "hardware-support"]
description = "HAL and Embassy support for the Py32 family of microcontrollers"
keywords = ["py32", "hal", "embedded", "no-std", "hardware-support"]
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
# py32-metapac = "0.1.1"
# py32-metapac = { path = "../py32-data/build/py32-metapac"}
py32-metapac = { git = "https://github.com/py32-rs/py32-metapac.git" }


cortex-m = { version = "0.7.7", features = [
    "critical-section-single-core",
    "critical-section",
] }
cortex-m-rt = "0.7.5"

embedded-hal-02 = { package = "embedded-hal", version = "0.2.6", features = [
    "unproven",
] }
embedded-hal-1 = { package = "embedded-hal", version = "1.0" }
embedded-hal-async = { version = "1.0" }
embedded-hal-nb = { version = "1.0" }
embedded-can = "0.4"
embedded-io = { version = "0.6.0" }
embedded-io-async = { version = "0.6.1" }
nb = "1.0.0"

defmt = { version = "0.3", optional = true }
defmt-rtt = { version = "0.4", optional = true }
log = { version = "0.4", optional = true }
critical-section = "1.2"
cfg-if = "1.0.0"


futures-util = { version = "0.3.30", default-features = false }
embassy-hal-internal = { version = "0.2.0", features = [
    "cortex-m",
    "prio-bits-4",
] }
embassy-sync = { version = "0.6.0", optional = true }
embassy-futures = { version = "0.1.1", optional = true }
embassy-time-driver = { version = "0.1.0", optional = true }
embassy-time = { version = "0.3.2", optional = true }
embassy-executor = { version = "0.6", features = [
    "nightly",
    "integrated-timers",
    "arch-cortex-m",
] }
embassy-embedded-hal = { version = "0.2.0", default-features = false }
embassy-usb-driver = {version = "0.1.0" }

[build-dependencies]
# py32-metapac = { path = "../py32-data/build/py32-metapac", default-features = false, features = [
# py32-metapac = { version = "0.1.1", default-features = false, features = [
py32-metapac = { git = "https://github.com/py32-rs/py32-metapac.git", default-features = false, features = [
    "metadata",
] }

proc-macro2 = "1.0.89"
quote = "1.0.37"

[features]
default = ["rt", "memory-x", "defmt", "embassy", "time", "exti"]

rt = ["py32-metapac/rt"]

defmt = ["dep:defmt", "dep:defmt-rtt", "embassy-usb-driver/defmt"]

memory-x = ["py32-metapac/memory-x"]

embassy = ["dep:embassy-sync", "dep:embassy-futures", "dep:embassy-time-driver"]


time = ["dep:embassy-time", "embassy-embedded-hal/time"]

exti = []

# PY32F07x: the IN and OUT buffers of the same endpoint being shared
# When this feature is enabled, the In and Out of an endpoint will not be used at the same time, except for ep0.
# PY32F403: IN and OUT do not share FIFO, this feature is invalid
allow-ep-shared-fifo = []

py32f030k28 = ["py32-metapac/py32f030k28"]
py32f030f16 = ["py32-metapac/py32f030f16"]
py32f072c1b = ["py32-metapac/py32f072c1b"]

# As of 2023-12-04, this driver is implemented using CC1 as the halfway rollover interrupt, and any
# additional CC capabilities to provide timer alarms to embassy-time. embassy-time requires AT LEAST
# one alarm to be allocatable, which means timers that only have CC1, such as TIM16/TIM17, are not
# candidates for use as an embassy-time driver provider. (a.k.a 1CH and 1CH_CMP are not, others are good.)
time-driver-any = ["_time-driver"]
time-driver-tim1 = ["_time-driver"]
time-driver-tim3 = ["_time-driver"]
time-driver-tim15 = ["_time-driver"]


_time-driver = []


[package.metadata.docs.rs]
default-target = "thumbv6m-none-eabi"
features = ["py32f030k28"]
