[package]
name = "py32-hal"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7.7", features = [
    "critical-section-single-core",
    "critical-section",
] }
cortex-m-rt = "0.7.3"

embedded-hal-02 = { package = "embedded-hal", version = "0.2.6", features = [
    "unproven",
] }
embedded-hal-1 = { package = "embedded-hal", version = "1.0" }
embedded-hal-async = { version = "1.0" }
embedded-hal-nb = { version = "1.0" }
embedded-can = "0.4"

defmt = { version = "0.3", optional = true }
defmt-rtt = { version = "0.4", optional = true }
log = { version = "0.4.14", optional = true }
critical-section = "1.2"

py32-metapac = { path = "../py32-data/build/py32-metapac" }

embassy-hal-internal = {version = "0.2.0", git = "https://github.com/embassy-rs/embassy.git" , features = ["cortex-m", "prio-bits-4"] }
embassy-sync = { version = "0.6.0", optional = true }
embassy-futures = { version = "0.1.1", optional = true }
embassy-time-driver = { version = "0.1.0", features = [
    "tick-hz-32_768",
], optional = true }
embassy-time = { version = "0.3.0", features = [
    "tick-hz-32_768",
], optional = true }
embassy-executor = { version = "0.6", features = [
    "nightly",
    "integrated-timers",
    "arch-cortex-m",
] }


[build-dependencies]
proc-macro2 = "1.0.36"
quote = "1.0.15"
py32-metapac = { path = "../py32-data/build/py32-metapac", default-features = false, features = [
    "metadata",
] }

[features]
default = ["rt", "memory-x", "time-driver-any", "defmt", "embassy"]

rt = ["py32-metapac/rt"]

defmt = ["dep:defmt", "dep:defmt-rtt"]

memory-x = ["py32-metapac/memory-x"]

embassy = [
    "dep:embassy-sync",
    "dep:embassy-futures",
    "dep:embassy-time-driver",
]

py32f030k28 = ["py32-metapac/py32f030k28"]
py32f030f16 = ["py32-metapac/py32f030f16"]

time-driver-any = ["_time-driver"]
time-driver-tim1 = ["_time-driver"]
time-driver-tim3 = ["_time-driver"]
time-driver-tim14 = ["_time-driver"]
time-driver-tim16 = ["_time-driver"]
time-driver-tim17 = ["_time-driver"]

_time-driver = []

