
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# TODO(2) replace `$CHIP` with your chip's name (see `probe-rs chip list` output)
runner = "probe-rs run --chip PY32F030x8"
# linker = "flip-link"


[build]
target = "thumbv6m-none-eabi"    # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "info"