[target.thumbv6m-none-eabi]
# probe-rs chip list | grep -i PY32
runner = 'probe-rs run --chip PY32F030x6'

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "info"

# rustflags = ["-C", "link-arg=-Tlink.x"]
